# Generated by Django 3.2.3 on 2021-05-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
